@TASKHEROAPI.Server_HostAddress = http://localhost:5097

GET {{TASKHEROAPI.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{TASKHEROAPI.Server_HostAddress}}/api/Users
Accept: application/json
###
